name: CI

on: [push]

env:
  ZIG_VERSION: 0.11.0-dev.3050+05ceac52c
  PIPING_SERVER_CHECK_VERSION: 0.13.1

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install zig
      run: |
        set -xeu
        cd /usr/local/bin/
        curl -L https://ziglang.org/builds/zig-linux-x86_64-${ZIG_VERSION}.tar.xz | sudo tar xJf -
        echo "PATH=$PATH:/usr/local/bin/zig-linux-x86_64-${ZIG_VERSION}" >> $GITHUB_ENV
    - name: Test
      run: find . -name '*.zig' | xargs -I{} zig test {}
      timeout-minutes: 1
    - run: zig build-exe -femit-bin=piping-server -O ReleaseSafe main.zig
    - name: Operational test
      run: |
        set -xeu
        # Start server
        ./piping-server &> server.log &
        sleep 2
        curl -sS localhost:8080

        seq 100 > data.txt
        cat data.txt | curl -sST- localhost:8080/mypath &
        curl -sS localhost:8080/mypath > data_transferred.txt
        diff data.txt data_transferred.txt
        cat data_transferred.txt
      timeout-minutes: 1
    - if: ${{ always() }}
      run: cat server.log
    - name: Install piping-server-check
      run: cd /tmp && wget -O piping-server-check.deb https://github.com/nwtgck/piping-server-check/releases/download/v${PIPING_SERVER_CHECK_VERSION}/piping-server-check-${PIPING_SERVER_CHECK_VERSION}-linux-amd64.deb && sudo dpkg -i piping-server-check.deb
    - name: piping-server-check (sometimes timeout)
      run: piping-server-check --http1.1 --concurrency 100 --server-command="${SERVER_COMMAND}" --n-simultaneous-requests=10 --transfer-speed-byte $((1024 * 1024 * 1024 * 1024)) --transfer-span 3s --transfer-span 10s --transfer-span 30s --compromise post_first.content_type_forwarding --compromise get_first.content_type_forwarding --compromise put.content_type_forwarding --compromise post_cancel_post --compromise get_cancel_get --compromise service_worker_registration_rejection --compromise multipart_form_data.content_type_forwarding --compromise multipart_form_data.content_disposition_forwarding --compromise multipart_form_data.transferred
      env:
        SERVER_COMMAND: 'mkdir -p /tmp/logs && exec ./piping-server $HTTP_PORT 2>&1 | tee /tmp/logs/$SERVER_RUN_ID.log > /dev/stderr'
      timeout-minutes: 1
    - name: Show server logs from piping-server-check
      if: ${{ always() }}
      run: tail -n +1 /tmp/logs/*
